export const MockSlicesTwo = [
    {
        id: 0,
        type: 1,
        angle: 40,
        offset: 0,
        backgroundColor: 'green',
        textColor: 'black',
        textFontSize: '14px',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 1,
        type: 2,
        angle: 40,
        offset: 0,
        backgroundColor: 'orange',
        textColor: 'blue',
        textFontSize: '14px',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 2,
        type: 3,
        angle: 40,
        offset: 0,
        backgroundColor: 'red',
        textColor: 'blue',
        textFontSize: '14px',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 3,
        type: 1,
        angle: 40,
        offset: 0,
        backgroundColor: 'darkBlue',
        textColor: 'lightBlue',
        textFontSize: '14px',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 4,
        type: 1,
        angle: 40,
        offset: 0,
        backgroundColor: 'brown',
        textColor: 'pink',
        textFontSize: '14px',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 5,
        type: 1,
        angle: 40,
        offset: 0,
        backgroundColor: 'blue',
        textColor: 'white',
        textFontSize: '14px',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 6,
        type: 2,
        angle: 40,
        offset: 0,
        backgroundColor: 'violet',
        textColor: 'rose',
        textFontSize: '14px',
       activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 7,
        type: 1,
        angle: 40,
        offset: 0,
        backgroundColor: 'grey',
        textColor: 'yellow',
        textFontSize: '14px',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 8,
        type: 3,
        angle: 40,
        offset: 0,
        backgroundColor: 'darkGreen',
        textColor: 'darkBlue',
        textFontSize: '14px',
        activated: false,
        selected: false,
        children: [],
        data: 0
    }
];
