export const MockSlicesTwoOrdered = [
    {
        id: 0,
        type: 1,
        angle: 40,
        offset: 0,
        backgroundColor: 'green',
        textColor: 'black',
        textFontSize: '80%',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 1,
        type: 1,
        angle: 40,
        offset: 0,
        backgroundColor: 'orange',
        textColor: 'black',
        textFontSize: '80%',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 2,
        type: 1,
        angle: 40,
        offset: 0,
        backgroundColor: 'red',
        textColor: 'black',
        textFontSize: '80%',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 3,
        type: 1,
        angle: 40,
        offset: 0,
        backgroundColor: 'darkBlue',
        textColor: 'black',
        textFontSize: '80%',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 4,
        type: 1,
        angle: 40,
        offset: 0,
        backgroundColor: 'brown',
        textColor: 'white',
        textFontSize: '80%',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 5,
        type: 1,
        angle: 40,
        offset: 0,
        backgroundColor: 'blue',
        textColor: 'white',
        textFontSize: '80%',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 6,
        type: 1,
        angle: 40,
        offset: 0,
        backgroundColor: 'violet',
        textColor: 'white',
        textFontSize: '80%',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 7,
        type: 1,
        angle: 40,
        offset: 0,
        backgroundColor: 'grey',
        textColor: 'white',
        textFontSize: '80%',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 8,
        type: 1,
        angle: 40,
        offset: 0,
        backgroundColor: 'darkGreen',
        textColor: 'white',
        textFontSize: '80%',
        activated: false,
        selected: false,
        children: [],
        data: 0
    }
];
