export const MockSlicesOne = [
    {
        id: 0,
        type: 1,
        angle: 45,
        offset: 0,
        backgroundColor: 'green',
        textColor: '',
        textFontSize: '16px',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 1,
        type: 2,
        angle: 20,
        offset: 0,
        backgroundColor: 'orange',
        textColor: 'blue',
        textFontSize: '12px',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 2,
        type: 3,
        angle: 10,
        offset: 0,
        backgroundColor: 'red',
        textColor: 'blue',
        textFontSize: '16px',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 3,
        type: 1,
        angle: 99,
        offset: 0,
        backgroundColor: 'darkBlue',
        textColor: 'blue',
        textFontSize: '16px',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 4,
        type: 1,
        angle: 31,
        offset: 0,
        backgroundColor: 'brown',
        textColor: 'green',
        textFontSize: '16px',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 5,
        type: 1,
        angle: 20,
        offset: 0,
        backgroundColor: 'blue',
        textColor: 'rose',
        textFontSize: '12px',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 6,
        type: 2,
        angle: 20,
        offset: 0,
        backgroundColor: 'violet',
        textColor: '',
        textFontSize: '12px',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 7,
        type: 1,
        angle: 40,
        offset: 0,
        backgroundColor: 'grey',
        textColor: 'black',
        textFontSize: '17px',
        activated: false,
        selected: false,
        children: [],
        data: 0
    },
    {
        id: 8,
        type: 3,
        angle: 75,
        offset: 0,
        backgroundColor: 'darkGreen',
        textColor: 'rose',
        textFontSize: '20px',
        activated: false,
        selected: false,
        children: [],
        data: 0
    }
];
